name: Release charts
on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  keycloak:
    uses: codecentric/helm-charts/.github/workflows/release-chart-base.yaml@master
    with:
      chart: keycloak
  mailhog:
    needs:
      - keycloak
    uses: codecentric/helm-charts/.github/workflows/release-chart-base.yaml@master
    with:
      chart: mailhog
